-- WARNING: Do NOT edit the input and output ports in this file in a text
-- editor if you plan to continue editing the block that represents it in
-- the Block Editor! File corruption is VERY likely to occur.

-- Copyright (C) 1991-2010 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions
-- and other software and tools, and its AMPP partner logic
-- functions, and any output files from any of the foregoing
-- (including device programming or simulation files), and any
-- associated documentation or information are expressly subject
-- to the terms and conditions of the Altera Program License
-- Subscription Agreement, Altera MegaCore Function License
-- Agreement, or other applicable license agreement, including,
-- without limitation, that your use is for the sole purpose of
-- programming logic devices manufactured by Altera and sold by
-- Altera or its authorized distributors.  Please refer to the
-- applicable agreement for further details.


-- Generated by Quartus II Version 9.1 (Build Build 304 01/25/2010)
-- Created on Fri Oct 25 11:37:53 2013

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


--  Entity Declaration

ENTITY licz IS
-- {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
PORT
(
  clk_dv : IN STD_LOGIC;
  p_licz : OUT STD_LOGIC;
  Q_licz : OUT STD_LOGIC_VECTOR(3 downto 0)
);
-- {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!

END licz;


--  Architecture Body

ARCHITECTURE licz_architecture OF licz IS

BEGIN
licz:
PROCESS (clk_dv)
VARIABLE i: INTEGER range 0 to 16;
BEGIN
IF clk_dv'EVENT AND clk_dv='1' THEN
i:=i+1;
IF i=10 THEN
p_licz<='1';
i:=0;
ELSE p_licz<='0';
END IF;
END IF;


Q_licz<=CONV_STD_LOGIC_VECTOR(i,4);
END PROCESS;
END licz_architecture;